baseURL: "https://imnajaniiiooo.github.io/"
title: "ÙˆØ¨Ù„Ø§Ú¯ Ø­Ø±ÙÙ‡â€ŒØ§ÛŒ Ù…Ù†"
languageCode: "fa-ir"
defaultContentLanguage: "fa"
theme: "hello-friend"

params:
  defaultTheme: "auto"
  displayFullLangName: false
  
  menu:
    main:
      - identifier: "home"
        name: "ğŸ  Ø®Ø§Ù†Ù‡"
        url: "/"
        weight: 1
      - identifier: "posts"
        name: "ğŸ“ Ù…Ù‚Ø§Ù„Ø§Øª"
        url: "/posts/"
        weight: 2
      - identifier: "about"
        name: "ğŸ‘¤ Ø¯Ø±Ø¨Ø§Ø±Ù‡ Ù…Ù†"
        url: "/about/"
        weight: 3

  socialIcons:
    - name: "github"
      url: "https://github.com/imnajaniiiooo"

pagination:
  pagerSize: 6
