baseURL: "https://imnajaniiiooo.github.io/"
title: "وبلاگ من"
languageCode: "fa-ir"
defaultContentLanguage: "fa"

theme: "PaperMod"

params:
  defaultTheme: auto
  profileMode:
    enabled: true
    title: "وبلاگ شخصی من"
    subtitle: "اینجا جایی است که افکار و تجربیاتم را به اشتراک می‌گذارم."
  
  socialIcons:
    - name: "github"
      url: "https://github.com/imnajaniiiooo"

menu:
  main:
    - identifier: "about"
      name: "درباره من"
      url: "/about/"
      weight: 10
    - identifier: "archives"
      name: "آرشیو"
      url: "/archives/"
      weight: 20

pagination:
  pagerSize: 5
